### ISSUE TITLE
how do i run it

### ISSUE THREAD

**Issue by makistoj** [ArthurG/KijijiPoster#1]
how do i run it???????????

**Comment by ArthurG** [comment]
Whats the error you're getting? Are you using Eclipse IDE?

**Comment by makistoj** [comment]
So I followed a tutorial. It's by Jim smith called import github Java project into eclipse and run it. I hope he showed the correct way to run it. Anyways I get a "bsh console" 
It says bean she'll 2.0b4 - by pat Niemeyer (pat@pat.net)
Bsh %
